version: "3.9"
services:
  server:
    container_name: roger_server
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/app
    env_file:
      - ./server/.env

  client:
    container_name: roger_client
    build: ./client
    ports:
      - "5173:5173"
    #volumes:
    #  - ./client:/usr/src/app
    #  - /usr/src/app/node_modules